# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - mkdir libs\mp11
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\mp11
  - python tools/boostdep/depinst/depinst.py mp11
  - bootstrap
  - b2 headers

build: off

test_script:
  - b2 libs/mp11/test toolset=msvc-14.0
